jQuery ->
  $('#width').parent().hide()
  $('#height').parent().hide()
  $('#url').parent().hide()
  $('#ad_text').parent().hide()
  $('#param_name').parent().hide()
  $('#param_restriction_value').parent().hide()
  $('#image').parent().hide()
  $('#clicks').parent().hide()
  if($('#advertisement_ad_type_image_link').attr('checked'))
    $('#width').parent().show()
    $('#height').parent().show()
    $('#url').parent().show()
    $('#image').parent().show()
    $('#clicks').parent().show()
  if($('#advertisement_ad_type_ad_service').attr('checked'))
    $('#ad_text').parent().show()
  if($('#advertisement_parameter_restriction_boolean_true').attr('checked'))
    $('#param_name').parent().show()
    $('#param_restriction_value').parent().show()

  $('#advertisement_ad_type_ad_service').change ->
    $('#width').parent().hide()
    $('#height').parent().hide()
    $('#url').parent().hide()
    $('#image').parent().hide()
    $('#clicks').parent().hide()
    $('#ad_text').parent().show()
  $('#advertisement_ad_type_image_link').change ->
    $('#width').parent().show()
    $('#height').parent().show()
    $('#url').parent().show()
    $('#image').parent().show()
    $('#clicks').parent().show()
    $('#ad_text').parent().hide()
  $('#advertisement_parameter_restriction_boolean_true').change ->
    $('#param_name').parent().show()
    $('#param_restriction_value').parent().show()
  $('#advertisement_parameter_restriction_boolean_false').change ->
    $('#param_name').parent().hide()
    $('#param_restriction_value').parent().hide()